### ISSUE TITLE
Dagit version update broke the pipeline 

### ISSUE THREAD

**Issue by sayantikabanik** [sayantikabanik/DataJourney#58]
Fix the issue 

```shell
Traceback (most recent call last):
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/bin/dagit", line 6, in <module>
    from dagster_webserver.cli import main
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster_webserver/cli.py", line 13, in <module>
    from dagster._cli.utils import get_possibly_temporary_instance_for_cli
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_cli/__init__.py", line 9, in <module>
    from dagster._cli.instance import instance_cli
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_cli/instance.py", line 8, in <module>
    from dagster._core.storage.migration.bigint_migration import run_bigint_migration
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_core/storage/migration/bigint_migration.py", line 6, in <module>
    from dagster._core.storage.event_log import SqlEventLogStorage, SqliteEventLogStorage
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_core/storage/event_log/__init__.py", line 1, in <module>
    from dagster._core.storage.event_log.base import (
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_core/storage/event_log/base.py", line 40, in <module>
    from dagster._core.storage.sql import AlembicVersion
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/dagster/_core/storage/sql.py", line 6, in <module>
    from alembic.command import downgrade, stamp, upgrade
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/runtime/migration.py", line 15, in <module>
    from .. import ddl
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql  # noqa
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/ddl/mssql.py", line 8, in <module>
    from .base import AddColumn
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/ddl/base.py", line 11, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/util/__init__.py", line 14, in <module>
    from .messaging import err  # noqa
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/util/messaging.py", line 8, in <module>
    from . import sqla_compat
  File "/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/alembic/util/sqla_compat.py", line 16, in <module>
    from sqlalchemy.sql.expression import _BindParamClause
ImportError: cannot import name '_BindParamClause' from 'sqlalchemy.sql.expression' (/Users/sayantikabanik/DataJourney/.pixi/envs/default/lib/python3.10/site-packages/sqlalchemy/sql/expression.py)

```

**Comment by sayantikabanik** [comment]
fixed #59
